version: "3.5"
services:

   app:
    build:
      context: .
      dockerfile: Dockerfile
#    env_file: .env
    volumes:
      - .:/app
#    ports:
#      - "${DJANGO_BIND_PORT}:${DJANGO_BIND_PORT}"
#    depends_on:
#      - db
    command:
      [
        "echo alo",
      ]