version: "3.5"
services:

  db:
    image: postgres:10.1-alpine

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command:
      [
        "echo alo",
      ]