version: "3.5"
services:

  db:
    image: postgres:10.1-alpine

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "${DJANGO_BIND_PORT}:${DJANGO_BIND_PORT}"
    command:
      [
        "./wait-for-it.sh",
        "${DB_HOST}:${DB_PORT}",
        "-t",
        "120",
        "--",
        "./start.sh",
      ]